application: tweepsect
version: 4
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /
  static_files: static/html/index.html
  upload: static/html/index.htm

#- url: .*
#  script: main.py
  
